export const temasPoliciaNacional = {
  1: "TEMA 01. EL DERECHO",
  2: "TEMA 02. CONSTITUCIÓN I",
  3: "TEMA 03. CONSTITUCIÓN II",
  4: "TEMA 04. UNIÓN EUROPEA",
  5: "TEMA 05. ADMINISTRACIÓN GENERAL DEL ESTADO",
  6: "TEMA 06. LOS FUNCIONARIOS PÚBLICOS",
  7: "TEMA 07. MINISTERIO DEL INTERIOR",
  8: "TEMA 08. DIRECCIÓN GENERAL POLICÍA",
  9: "TEMA 09. LEY ORGÁNICA 2/1986 DE FUERZAS Y CUERPOS DE SEGURIDAD",
  10: "TEMA 10. EXTRANJERÍA I",
  11: "TEMA 11. EXTRANJERÍA II",
  12: "TEMA 12. PROTECCIÓN INTERNACIONAL",
  13: "TEMA 13. SEGURIDAD PRIVADA",
  14: "TEMA 14. SEGURIDAD CIUDADANA",
  15: "TEMA 15. INFRAESTRUCTURAS CRÍTICAS",
  16: "TEMA 16. DERECHO PENAL GENERAL",
  17: "TEMA 17. HOMICIDIO Y SUS FORMAS",
  18: "TEMA 18. DELITOS CONTRA PATRIMONIO",
  19: "TEMA 19. DELITOS CONTRA EL ORDEN PÚBLICO",
  20: "TEMA 20. DELITOS INFORMÁTICOS",
  21: "TEMA 21. DERECHO PROCESAL PENAL",
  22: "TEMA 22. ESTATUTO DE LA VÍCTIMA DEL DELITO",
  23: "TEMA 23. VIOLENCIA DE GÉNERO",
  24: "TEMA 24. INTRODUCCIÓN PREVENCIÓN DE RIESGOS LABORALES",
  25: "TEMA 25. PREVENCIÓN DE RIESGOS LABORALES",
  26: "TEMA 26. PROTECCIÓN DE DATOS",
  27: "TEMA 27. DERECHOS HUMANOS",
  28: "TEMA 28. GLOBALIZACIÓN",
  29: "TEMA 29. ACTITUDES",
  30: "TEMA 30. PRINCIPIOS ÉTICOS",
  31: "TEMA 31. MIGRACIONES",
  32: "TEMA 32. LA CIUDAD",
  33: "TEMA 33. LA SEGURIDAD",
  34: "TEMA 34. DROGAS",
  35: "TEMA 35. DESARROLLO SOSTENIBLE",
  36: "TEMA 36. GRAMÁTICA",
  37: "TEMA 37. ORTOGRAFÍA",
  38: "TEMA 38. SISTEMAS OPERATIVOS",
  39: "TEMA 39. REDES INFORMÁTICAS",
  40: "TEMA 40. INTELIGENCIA",
  41: "TEMA 41. CIBERDELINCUENCIA",
  42: "TEMA 42. ARMAS DE FUEGO",
  43: "TEMA 43. VEHÍCULO PRIORITARIO",
  44: "TEMA 44. SEGURIDAD CONDUCCIÓN",
  45: "TEMA 45. PREVENCIÓN DE RIESGOS LABORALES EN LA SEGURIDAD VIAL",
};

// Aquí puedes crear otros objetos para Guardia Civil o Funcionario de prisiones
export const temasGuardiaCivil = {
  1: "Derechos humanos",
  2: "Igualdad efectiva de mujeres y hombres",
  3: "Prevención de riesgos laborales",
  4: "Derecho constitucional",
  5: "Derecho de la Unión Europea",
  6: "Instituciones internacionales",
  7: "Derecho civil",
  8: "Derecho penal",
  9: "Derecho procesal penal",
  10: "Derecho administrativo",
  11: "Protección de datos",
  12: "Extranjería e inmigración",
  13: "Seguridad pública y seguridad privada",
  14: "Ministerio del Interior y Ministerio de Defensa",
  15: "Fuerzas y Cuerpos de Seguridad. Guardia Civil",
  16: "Materias socio-culturales. Protección Civil. Desarrollo sostenible. Eficiencia energética",
  17: "Materias técnico-científicas. Tecnologías de la información y la comunicación",
  18: "Topografía",
  19: "Deontología profesional",
  20: "Responsabilidad penal de los menores",
  21: "Protección integral contra la violencia de género",
  22: "Armas y explosivos",
  23: "Derecho fiscal",
  24: "Inglés",
  25: "Lengua española"
};

export const temasFuncionarioPrisiones = {
  // Primera Parte: Organización del Estado y Administración Pública
  1: "Constitución Española de 1978",
  2: "El Poder Judicial",
  3: "El Gobierno",
  4: "Organización territorial del Estado",
  5: "La Unión Europea",
  6: "Estructura orgánica del Ministerio del Interior",
  7: "El personal de Instituciones Penitenciarias",
  8: "Régimen jurídico del personal al servicio de las Administraciones Públicas",
  9: "Acceso al empleo público",
  10: "Contratos del Sector Público",
  11: "Ley 45/2015, de 14 de octubre, de Voluntariado",
  12: "Políticas Públicas",
  13: "Gobierno abierto",
  14: "Actividad de las Administraciones Públicas",
  15: "Fuentes del Derecho Administrativo",
  16: "Régimen Jurídico del Sector Público",
  17: "El Presupuesto",

  // Segunda Parte: Derecho Penal
  18: "El Derecho Penal. Garantías penales y de aplicación de la Ley Penal",
  19: "Delitos: concepto y clases. Grados de ejecución",
  20: "Personas criminalmente responsables de los delitos",
  21: "Formas de suspensión de la ejecución de las penas privativas de libertad",
  22: "Medidas de seguridad. Extinción de la responsabilidad criminal",
  23: "Principales delitos (1)",
  24: "Principales delitos (2)",
  25: "Delitos contra la Administración Pública, Administración de Justicia, Instituciones del Estado y derechos fundamentales",
  26: "Jurisdicción penal. Proceso penal. Procedimiento ordinario y abreviado. Habeas Corpus",
  27: "Recursos: reforma, apelación, súplica, queja, casación, revisión y amparo",

  // Segunda Parte: Derecho Penitenciario
  28: "Regulación supranacional en materia penitenciaria",
  29: "Derecho Penitenciario",
  30: "Relación jurídico-penitenciaria. Derechos y deberes de los internos",
  31: "Prestaciones de la Administración Penitenciaria",
  32: "Régimen Penitenciario (1)",
  33: "Régimen Penitenciario (2)",
  34: "Clasificación de establecimientos y sus características",
  35: "Régimen cerrado y régimen abierto",
  36: "Tratamiento Penitenciario (1)",
  37: "Tratamiento Penitenciario (2)",
  38: "Relación laboral en el medio penitenciario",
  39: "Permisos de salida",
  40: "Libertad y excarcelación en sus distintas formas",
  41: "Formas especiales de ejecución de la pena de prisión",
  42: "Régimen disciplinario. Procedimiento sancionador. Recompensas",
  43: "Control de la actividad penitenciaria por el Juez de Vigilancia",
  44: "Modelo organizativo penitenciario",
  45: "Régimen administrativo de los Establecimientos Penitenciarios (1)",
  46: "Régimen administrativo de los Establecimientos Penitenciarios (2)",
  47: "Régimen económico de los Establecimientos Penitenciarios"
};
